---
abstract: 'Recursively enumerate graphite metrics'
author:
  - unknown
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Graphite-Enumerator
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/rgs/Graphite-Enumerator.git
version: '0.03'
